[package]
name = "example-sse"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["sse"] }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.17"
tokio-stream = "0.1.7"
tracing-subscriber = { version ="0.3.9", features = ["env-filter"] }
